#!/bin/sh

process () {
  read width height <<<$(getImageDimensions "$1")
  dWidth=$(($backgroundWidth - $width))
  dHeight=$(($backgroundHeight - $height))
  if [ "$dWidth" -lt 0 ] || [ "$dWidth" -lt 0 ]
  then
    echo "error" 1>&2
    exit 1
  fi
  convert \( -size "$width"x"$height" xc:black \) \
    \( "$background" \
      -chop $(random $(($dWidth + 1)))x$(random $(($dHeight + 1))) \) \
    "$1" -composite test.png
}

getImageDimensions () {
  echo $(identify -verbose "$1" | \
    sed -En 's/^  Geometry: ([0-9]+)x([0-9]+)\+0\+0$/\1 \2/p')
}

random () {
  echo $(( \
    $(dd if=/dev/urandom count=1 2> /dev/null | cksum | cut -f1 -d" ") % $1))
}

if [ -f background.png ]
then
  background=background.png
fi

if [ -z "$background" ];
then
  echo "error" 1>&2
  exit 1
fi

read backgroundWidth backgroundHeight <<<$(getImageDimensions "$background")
echo $backgroundWidth
echo $backgroundHeight

find in -mindepth 1 | while read file; do process "$file"; done

echo $(random 10)
