#!/bin/bash

process () {
  read width height saturation <<< \
    $(convert "in/$1" -colorspace HSL -format '%w %h %[fx:mean.g]' info:)

  if [ "${saturation#*"e"}" != "$saturation" ] || \
    [ $(echo "$saturation < 0.25" | bc) -ne 0 ]
  then
    dWidth=$(($backgroundWidth - $width))
    dHeight=$(($backgroundHeight - $height))
    if [ "$dWidth" -lt 0 ] || [ "$dHeight" -lt 0 ]
    then
      error "background file too small"
    fi
    convert \( -size "$width"x"$height" xc:black \) \
      \( "$background" \
        -chop $(random $(($dWidth + 1)))x$(random $(($dHeight + 1))) \) \
      \( "in/$1" $(level) \) -composite "out/$(rename "$1")"
  else
    cp "in/$1" "out/$(rename "$1")"
  fi
}

rename () {
  echo $1 | sed 's/\///g'
}

random () {
  echo $(( \
    $(dd if=/dev/urandom count=1 2> /dev/null | cksum | cut -f1 -d" ") % $1))
}

level () {
  if [ -n "$gamma" ]
  then
    echo "-level 0%,100%,$gamma"
  fi
}

countFilesInZip () {
  unzip -l "$1" | tail -n 1 | \
    sed -En 's/^ *[0-9]+ +([0-9]+) files/\1/p'
}

error () {
  echo "error: $1" 1>&2
  exit 255
}

while getopts "g:" OPTION
do
  case $OPTION in
    g) gamma=$OPTARG ;;
    \?) error "usage error" ;;
  esac
done

if [ -f background.png ]
then
  background=background.png
fi

if [ -z "$background" ]
then
  error "no background file"
fi

inputFile=${!OPTIND}
if [ -z "$inputFile" ]
then
  error "please specify input file"
fi

rm -rf in out
mkdir in out

unzip -d in "$inputFile"

read backgroundWidth backgroundHeight <<< \
  $(convert "$background" -colorspace HSL -format '%w %h' info:)

export background
export backgroundWidth
export backgroundHeight
export gamma

export -f process
export -f rename
export -f random
export -f level
export -f error

outputFile=$(basename "$(echo "$1" | sed 's/\(.*\)\.\(.*\)/\1/')"_converted.zip)

find in -type f | sed 's/^in\///g;s/"/\\\"/g;s/\\/\\\\\\/g' | \
  tail -n 5 | \
  xargs \
    -P $(cat /proc/cpuinfo | grep '^processor	' | wc -l) \
    -I {} bash -c "process \"{}\""

cd out
zip -r "../$outputFile" .
cd ..

if [ $(countFilesInZip "$inputFile") -ne $(countFilesInZip "$outputFile") ]
then
  error "number of ouput files does not match input files"
fi

rm -rf in out
#remove old zip
# remove zip + temp on error
